// Generated by CoffeeScript 1.3.1
(function() {
  var Pilas, pilas;

  Pilas = (function() {

    Pilas.name = 'Pilas';

    function Pilas() {}

    Pilas.prototype.iniciar = function(elemento) {
      alert(elemento);
      this.canvas = document.getElementById(elemento);
      this.stage = new Stage(this.canvas);
      return alert('asdasd');
    };

    return Pilas;

  })();

  pilas = new Pilas;

}).call(this);
