// Generated by CoffeeScript 1.4.0
(function() {

  define(['libs/Box2dWeb-2.1.a.3.js'], function(_box2d) {
    var Fisica;
    Fisica = (function() {

      function Fisica() {}

      Fisica.prototype.example = function(a, b) {
        this.a = a;
        return this.b = b;
      };

      return Fisica;

    })();
    return Fisica;
  });

}).call(this);
